site_name: Too Lazy to Write
site_url: https://2lazy2write.github.io
nav:
    - Home: index.md
    - 现代车.md
    - 我的故事.md
theme:
  name: material
  language: zh
  palette:
    primary: teal
  font: 
    text: Noto Serif SC
extra_css:
    - extra.css
markdown_extensions:
    - footnotes
    - admonition
    - pymdownx.details